cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('add/ajax/', views.cart_add_ajax, name='cart_add_ajax'),
    path('remove/ajax/',views.cart_remove_ajax, name='cart_remove_ajax'),
    path('clear/', views.cart_clear, name='cart_clear'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupon'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

maa_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from accounts.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payments/', include('payments.urls', namespace='payments')),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('products.urls', namespace='products')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('summary/', views.order_summary, name='order_summary'),
    path('create/<int:adr_id>', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    path('incomplete/order/<int:order_id>/', views.user_pending_order_action, name='pending_order'),
    path('incomplete/order/update/<int:adr_id>/<int:order_id>/', views.user_pending_order_update, name='pending_order_update'),
    path('cancel/incomplete/<int:order_id>/', views.cancel_pending_order, name='cancel_pending_order'),
    # path('created/', views.order_created, name='order_created'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = ( (i, str(i)) for i in range(1, 21))

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label="",choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update   = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput())

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse

from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponForm

# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add( product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

@login_required
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'update': True
        })
    coupon_form = CouponForm()
    return render(request, "cart/cart_detail.html", {'cart': cart, 'coupon_form': coupon_form})


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')

@require_POST
def cart_add_ajax(request):
    data = {}
    cart = Cart(request)
    product_id = request.POST.get("product_id")
    try:
        product = Product.objects.get(id=product_id)
    except Product.DoesNotExist:
        product = None
        data['added'] = 'ko'
        data['error_message'] = 'product does not exists'
        return JsonResponse(data, safe=False)
    
    if product:
        update_quan = cart.item_in_cart(product_id)
        item_quan = cart.item_quantity_in_cart(product_id)
        quantity = 1+item_quan
        cart.add(product=product,
                 quantity=quantity, update_quantity=update_quan)
        data['added'] = 'ok'
    
        data['added_item'] = {
            'cart_item_product_id': str(product.id),
            'product_name': " ".join(str(product.name).split()[:2]) + " ...",
            'product_url': str(product.get_absolute_url()),
            'product_image_url': str(product.image.url),
            'quantity': str(quantity),
            'price': str(product.get_price())
        }
        data['cart_total'] = str(cart.get_total_price())
        data['cart_length'] = str(len(cart))
        return JsonResponse(data, safe=False)

@require_POST
def cart_remove_ajax(request):
    data = {}
    cart = Cart(request)
    product_id = request.POST.get("product_id")
    try:
        product = Product.objects.get(id=product_id)
    except Product.DoesNotExist:
        product = None
        data['removed'] = 'ko'
        data['error_message'] = 'product doest not exist'
        return JsonResponse(data, safe=False)
    if product and cart.item_in_cart(product.id):
        cart.remove(product)
        data['removed'] = 'ok'
        data['cart_item_product_id'] = str(product.id)
        data['cart_total'] = str(cart.get_total_price())
        data['cart_length'] = str(len(cart))
        return JsonResponse(data, safe=False)
    else:
        data['removed'] = 'ko'
        data['error_message']='Item not present in cart'
        return JsonResponse(data, safe=False)

cart/templates/cart/cart_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block extrastyles %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="{% static 'cart/cart_detail.css' %}">
{% endblock %}
{% block page_title %}Cart-detail - Maa Shop{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="page-header">
        <h1>shopping cart</h1>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-8">
            <div class="cart-table-container">
                <table class="table table-cart">
                    <thead>
                        <tr>
                            <th class="product-col">Product</th>
                            <th class="qty-col">Qty</th>
                            <th>Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% if cart %}
                            {% for item in cart %}
                                {% with product=item.product %}
                                    <tr class="product-row">
                                        <td class="product-col">
                                            <div class="product-image-container">
                                                <a href="{{ product.get_absolute_url }}" class="produt-table-image">
                                                    <img src="{{ product.image.url }}" alt="" srcset="">
                                                </a>
                                            </div>
                                            <div class="product-title">
                                                <a href="">{{ product.name|truncatewords:"3" }}</a>
                                                <br><span class="text-muted small">
                                                    {{ item.quantity }} x ${{ item.price }}
                                                    </span>
                                            </div>
                                        </td>
                                        <td class="qty-col">
                                            <div class="change-qty">
                                                <form class="form-inline" action="{% url 'cart:cart_add' product.id %}" method="post">
                                                    {% csrf_token %}
                                                    <div class="form-group">
                                                        {{ item.update_form.quantity|as_crispy_field }}
                                                        {{ item.update_form.update }}
                                                    </div>
                                                </form>
                                            </div>
                                        </td>
                                        <td>${{ item.total_price }}</td>
                                    </tr>
                                    <tr class="product-row-action">
                                        <td colspan="4" class="clearfix">
                                            <div class="float-left">
                                                <a href="#" class="btn-move">Move to Wishlist</a>
                                            </div>
                                        
                                            <div class="float-right">
                                                <a href="#" title="Edit product" class="btn-edit">
                                                <a href="{% url 'cart:cart_remove' product.id %}" title="Remove product" class="btn-remove">
                                                    <i class="fa fa-times"></i>
                                                    <span class="sr-only">Remove</span>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                        {% else %}
                            <tr>
                                <td colspan="3">Nothing in Cart!</td>
                            </tr>
                        {% endif %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3">
                                <div class="cart-table-footer">
                                    <div class="left">
                                        <a href="/" class="btn btnD1">Continue Shopping</a>
                                    </div>
                                    {% if cart %}
                                    <div class="right">
                                        <a href="{% url 'cart:cart_clear' %}" class="btn btnD1 btn-clear-cart">Clear Shopping Cart</a>
                                    </div>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- apply discount form -->
            <div class="row">
                <div class="col-12">
                    <div class="apply-coupon-box">
                        <h4>Apply Discount coupon</h4>
                        <form action="{% url 'coupons:apply' %}" method="post" class="form-inline mt-3">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ coupon_form|crispy }}
                            </div>
                            <button type="submit" class="btn btnD2 m-0">Apply discount</button>
                        </form>
                    </div>
                </div>
            </div>
            <!-- end apply discount form -->
        </div>
        <div class="col-lg-4">
            <div class="cart-summary">
                <h3>Summary</h3>            
                <table class="table table-totals">
                    <tbody>
                        <tr>
                            <td>Subtotal</td>
                            <td>${{ cart.get_total_price|floatformat:"2" }}</td>
                        </tr>
                        {% if cart.coupon %}
                            <tr>
                                <td>{{ cart.coupon.code }} coupon ({{ cart.coupon.discount }}%)</td>
                                <td>-${{ cart.get_discount|floatformat:"2" }}</td>
                            </tr>
                            {% with active=cart.coupon.is_active %}
                                <tr class="coupon coupon-{% if active %}active{% else%}expired{% endif %}">
                                    <td>
                                        Valid upto:- <span>{{ cart.coupon.valid_to|date:"D, d M,h a" }}</span>
                                    </td>
                                    <td>
                                        {% if active %} Applied {% else %} Expired {% endif %}
                                    </td>
                                </tr>
                            {% endwith %}
                        {% endif %}
                        <tr>
                            <td>Tax</td>
                            <td>$0.00</td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td>Order Total</td>
                            <td>${{ cart.get_total_price_after_discount|floatformat:"2"}}</td>
                        </tr>
                    </tfoot>
                </table>
            
                <div class="checkout-methods">
                    <a href="{% url 'orders:order_summary' %}" class="btn w-100 btnD2">Go to Checkout</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
{% block extra_scripts %}
    <script>
        $('select').on('change', function(e){
            var formElement = $(this).parent().parent().parent().parent();
            formElement.submit();
        });
    </script>
{% endblock %}