accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('activate/<uid>/<token>/', views.activate, name='activate'),
    path('myaddress/', views.list_user_address, name='address_list'),
    path('address/create/', views.add_user_address, name='address_create'),
    path('address/edit/<int:adr_id>/', views.edit_user_address, name='address_edit'),
    path('address/delete/<int:adr_id>/', views.delete_user_address, name='address_delete'),
    path('address/delete/ajax/', views.delete_user_address_ajax, name='address_delete_ajax'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('add/ajax/', views.cart_add_ajax, name='cart_add_ajax'),
    path('remove/ajax/',views.cart_remove_ajax, name='cart_remove_ajax'),
    path('clear/', views.cart_clear, name='cart_clear'),
]

maa_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from accounts.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payments/', include('payments.urls', namespace='payments')),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('products.urls', namespace='products')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('summary/', views.order_summary, name='order_summary'),
    path('create/<int:adr_id>', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    path('incomplete/order/<int:order_id>/', views.user_pending_order_action, name='pending_order'),
    path('incomplete/order/update/<int:adr_id>/<int:order_id>/', views.user_pending_order_update, name='pending_order_update'),
    path('cancel/incomplete/<int:order_id>/', views.cancel_pending_order, name='cancel_pending_order'),
    # path('created/', views.order_created, name='order_created'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('products/', views.product_list, name='product_list'),
    path('products-by-category/<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('products/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('product-detail/ajax/<int:product_id>/', views.product_quick_detail_ajax,name='product_quick_detail_ajax')
]

orders/models.py
from django.db import models
from products.models import Product
from accounts.models import UserAddress
from django.contrib.auth import get_user_model
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from coupons.models import Coupon

from uuid import uuid4

# Create your models here.

User = get_user_model()

class Order(models.Model):
    user        = models.ForeignKey(User, related_name='orders', on_delete=models.CASCADE, null=True)
    address     = models.ForeignKey(UserAddress, related_name="orders", on_delete=models.CASCADE)
    created     = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)
    paid        = models.BooleanField(default=False)
    coupon      = models.ForeignKey(Coupon, related_name='orders', null=True, blank=True, on_delete=models.SET_NULL)
    discount    = models.IntegerField(default=0, validators=[MinValueValidator(5), MaxValueValidator(100)])
    paytm_txn_id= models.CharField(max_length=255, blank=True, null=True)
    paytm_order_id = models.CharField(max_length=255, blank=True, null=True)
    cancelled      = models.BooleanField(default=False)
    txn_time    = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ('-created',)
    
    def __str__(self):
        return f'Order no {self.id} from {self.address.full_name}'
    
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())
    
    def get_discount(self):
        total_cost = self.get_total_cost()
        return total_cost * (self.discount / Decimal('100'))

    def get_total_cost_after_discount(self):
        total_cost = self.get_total_cost()
        disc = self.get_discount() if self.coupon else 0
        return total_cost - disc

    def set_unique_paytm_order_id(self):
        ord_id = uuid4().hex
        if not Order.objects.filter(paytm_order_id=ord_id).exists():
            self.paytm_order_id = ord_id
            self.save()
            return self.paytm_order_id
        return self.set_unique_paytm_order_id()
        
    
    def get_unqiue_paytm_order_id(self):
        return self.paytm_order_id

class OrderItem(models.Model):
    order   = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name="order_items", on_delete=models.CASCADE)
    price   = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    
    def __str__(self):
        return f'{self.id}'
    
    def get_cost(self):
        return self.price * self.quantity

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.conf import settings
from django.urls import reverse
from django.template.loader import render_to_string
from django.http import HttpResponse
from django.contrib import messages
import weasyprint

from accounts.forms import UserAddressForm
from accounts.models import UserAddress
from .models import OrderItem, Order
from cart.cart import Cart
from .tasks import send_invoice_order
from coupons.models import Coupon
from .decorators import no_active_order_redirect

# Create your views here.

User = get_user_model()

@login_required
@no_active_order_redirect
def order_summary(request):
    cart = Cart(request)
    user = request.user
    address_list = user.addresses.order_by('-created')
    modal = False
    if request.method == 'POST':
        modal = True
        address_form = UserAddressForm(request.POST)
        if address_form.is_valid():
            print('form is valid')
            address = address_form.save(commit=False)
            address.user = user
            address.save()
            return redirect('orders:order_summary')
    else:
        address_form = UserAddressForm()
    context = {
        'cart': cart,
        'address_form': address_form,
        'address_list': address_list,
        'modal': modal,
    }
    return render(request, "orders/order_summary.html", context=context)


@login_required
@no_active_order_redirect
def order_create(request, adr_id):
    cart = Cart(request)
    user = request.user
    address = get_object_or_404(UserAddress, id=adr_id)
    order = Order.objects.create(user=user, address=address)
    for item in cart:
        product = item['product']
        quantity = item['quantity']
        OrderItem.objects.create(order=order, product=product, price=item['price'],
                                 quantity=quantity)
        product.stock -= quantity
        product.save()
    # if cart has discount coupon applicable then save its info on order 
    if cart.coupon and cart.coupon.is_active():
        order.coupon = cart.coupon
        order.discount = cart.coupon.discount
        order.save()

    cart.clear()
    send_invoice_order.delay(order.id)  # launchinf async task
    return redirect(reverse('payments:process', kwargs={'order_id': order.id}))


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, "orders/admin/order_detail.html", {'order': order})


@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/order_invoice.html', {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=order_{order.id}.pdf'
    weasyprint.HTML(string=html).write_pdf(response, stylesheets=[
        weasyprint.CSS(settings.STATIC_ROOT +'\\' + 'css/order_invoice.css')
    ])
    return response

@login_required
def user_pending_order_action(request, order_id):
    user = request.user
    order = get_object_or_404(Order, id=order_id)
    address_list = user.addresses.order_by('-created')
    modal = False
    if request.method == 'POST':
        modal = True
        address_form = UserAddressForm(request.POST)
        if address_form.is_valid():
            print('form is valid')
            address = address_form.save(commit=False)
            address.user = user
            address.save()
            return redirect('orders:pending_order')
    else:
        address_form = UserAddressForm()

    msg = '''You have an incompleted Order, 
            before making any other orders Please complete this order by making 
            payment or cancelling the Order!'''
    context = {
        'order': order,
        'address_form': address_form,
        'address_list': address_list,
        'modal': modal
    }
    messages.info(request, msg)
    return render(request, "orders/pending_order.html", context=context)

@login_required
def user_pending_order_update(request, adr_id, order_id):
    user = request.user
    address = get_object_or_404(UserAddress, id=adr_id)
    order = get_object_or_404(Order, id=order_id)
    if order.address != address:
        order.address = address
        order.save()
    # send updated order invoice
    send_invoice_order.delay(order.id)
    return redirect(reverse('payments:process', kwargs={'order_id': order.id}))


@login_required
def cancel_pending_order(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    order.cancelled = True
    order.save()
    return redirect('/')

orders/templates/orders/order_created.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block extrastyles %}
{% endblock %}
{% block page_title %}Order-created - Maa Shop{% endblock %}
{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <p class="lead">
            Your Order has been successfully created. Your Order no. is {{ order.id }}
        </p>
    </div>

</div>
{% endblock %}

orders/templates/orders/order_summary.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block extrastyles %}
    <link rel="stylesheet" href="{% static 'orders/order_create.css' %}">

{% endblock %}
{% block page_title %}Order - Maa Shop{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="page-header">
        <h1>checkout</h1>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-8">
            <div class="row">
                <div class="col-12">
                    <h2 class="display-4  border-bottom" style="font-size: 2rem;">Shipping Address</h2>
                </div>
            </div>
            <div class="row">
                {% if address_list %}
                    {% for adr in address_list %}
                        <div class="col-12 col-md-4">
                            <div class="address-box" id="address-box-{{ adr.id }}">
                                <address>
                                    {{ adr.full_name|title }} <br>
                                    {{ adr.line_1 }}, {{ adr.city }} <br>
                                    {{ adr.state }}, {{ adr.pin_code }} <br>
                                    {{ adr.phone }}
                                </address>
                                <div class="remove-btn">
                                    <a href="" data-address-id="{{ adr.id }}" ><i class="fa fa-times"></i></a>
                                </div>
                                <div class="address-action">
                                    <a href="{% url 'accounts:address_edit' adr.id %}" class="btn btn-sm"><i class="fa fa-pencil" aria-hidden="true"></i> Edit</a>
                                    <a href="{% url 'orders:order_create' adr.id %}" class="btn btnD1">Deliver Here</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="row">
                <div class="mt-4 ml-3">
                    <button type="button" class="btn btnD2" data-toggle="modal" data-target="#newAddressModal">
                        <i class="fa fa-plus" aria-hidden="true"></i> New Address
                    </button>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
			<div class="order-summary">
                <h3 style="font-size: 1.2rem; font-weight: 300;">Summary</h3>
                <h4>
                    <a class="btn w-100 d-flex justify-content-between border-bottom border-top" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false"
                        aria-controls="collapseExample">
                        {% with length=cart|length %}
                        <span>{{ length }} product{{ length|pluralize }} in Cart</span>
                        <span><i class="fa fa-angle-down" aria-hidden="true"></i></span>
                        {% endwith %}
                    </a>
                </h4>
                <div class="collapse" id="collapseExample">
                    <table class="table table-mini-cart">
                        <tbody>
                            {% for item in cart %}
                                {% with product=item.product %}
                                    <tr>
                                        <td class="product-col">
                                            <div class="product-image-container">
                                                <a href="{{ product.get_absolute_url }}">
                                                    <img src="{{ product.image.url }}" alt="">
                                                </a>
                                            </div>
                                            <div>
                                                <h4>
                                                    <a href="{{ product.get_absolute_url }}">
                                                        {{ product.name|truncatewords:"2" }}
                                                    </a>
                                                </h4>
                                                <span class="product-qty">Qty: {{ item.quantity }}</span>
                                            </div>
                                        </td>
                                        <td class="price-col">
                                            ${{ item.total_price|floatformat:"2" }}
                                        </td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="2" style="padding: 0;">
                                    <a href="{% url 'cart:cart_detail' %}" class="btn btnD1 w-100">Change quantity or product</a>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
			</div>
		</div>
    </div>
</div>

<!-- Modal for new address -->
<div class="modal fade bd-example-modal-lg" id="newAddressModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add New Address</h5>
            </div>
            <div class="modal-body">
                <form method="post" id="addressModalForm">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-12 col-lg-12">
                            {{ address_form.full_name|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-lg-3 mb-0">
                            {{ address_form.country_code|as_crispy_field }}
                        </div>
                        <div class="form-group col-lg-5 mb-0">
                            {{ address_form.phone|as_crispy_field }}
                        </div>
                        <div class="form-group col-lg-4 mb-0">
                            {{ address_form.pin_code|as_crispy_field }}
                        </div>
                    </div>
                    {{ address_form.line_1|as_crispy_field }}
                    {{ address_form.line_2|as_crispy_field }}
                    <div class="form-row">
                        <div class="form-group col-lg-3 mb-0">
                            {{ address_form.landmark|as_crispy_field }}
                        </div>
                        <div class="form-group col-lg-4 mb-0">
                            {{ address_form.city|as_crispy_field }}
                        </div>
                        <div class="form-group col-lg-5 mb-0">
                            {{ address_form.state|as_crispy_field }}
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btnD1" data-dismiss="modal">Close</button>
                <button type="button" class="btn btnD2" id="newAddressBtn">Save</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block extra_scripts %}
    <script>
        $(document).ready(function(){

            var showModal = "{{ modal }}";
            if (showModal == "True"){
                $("#newAddressModal").modal('show');
            }
            
            $(".address-box").first().addClass('active');
            $(".address-box").on("click", function(e){
                $(this).parent().siblings().children().removeClass('active');
                $(this).addClass('active');
            });

            $("#newAddressModal input").addClass("form-control-sm");
            $("#newAddressModal select").addClass("form-control-sm");

            $(".remove-btn a").on('click', function(e){
                e.preventDefault();
                var adr_id = parseInt($(this).data("address-id"));

                $.post({
                    url: "{% url 'accounts:address_delete_ajax' %}",
                    data: {
                        'adr_id': adr_id,
                    },
                    dataType: 'json',
                    success: function(data){
                        if(data['status']=='ok'){
                            console.log('address deleted');
                            $("#address-box-"+adr_id).parent().remove();
                            alert("Address Deleted successfully!")
                        }else{
                            alert('Sorry, Something went wrong!');
                        }
                    }
                })
            });

            $("#newAddressBtn").on('click', function(){
                $("#addressModalForm").submit();
            });

            $("#newAddressModal").on('shown.bs.modal', function(){
                $('.header-nav').css('display', 'none');
            });
            $("#newAddressModal").on('hidden.bs.modal', function(){
                $('.header-nav').css('display', 'block');
            });
        });
        // add onchange validation for fields
        // id_phone 
        // id_pin_code
    </script>
{% endblock %}

orders/templates/orders/pending_order.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block extrastyles %}
<link rel="stylesheet" href="{% static 'orders/order_create.css' %}">

{% endblock %}
{% block page_title %}Order - Maa Shop{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="page-header">
        <h1>checkout</h1>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-8">
            <div class="row">
                <div class="col-12">
                    <h2 class="display-4  border-bottom" style="font-size: 2rem;">Shipping Address</h2>
                </div>
            </div>
            <div class="row">
                {% if address_list %}
                {% for adr in address_list %}
                <div class="col-12 col-md-4">
                    <div class="address-box {% if adr.id == order.address.id %}active{% endif %}" id="address-box-{{ adr.id }}">
                        <address>
                            {{ adr.full_name|title }} <br>
                            {{ adr.line_1 }}, {{ adr.city }} <br>
                            {{ adr.state }}, {{ adr.pin_code }} <br>
                            {{ adr.phone }}
                        </address>
                        <div class="remove-btn">
                            <a href="" data-address-id="{{ adr.id }}"><i class="fa fa-times"></i></a>
                        </div>
                        <div class="address-action">
                            <a href="{% url 'accounts:address_edit' adr.id %}" class="btn btn-sm"><i
                                    class="fa fa-pencil" aria-hidden="true"></i> Edit</a>
                            <a href="{% url 'orders:pending_order_update' adr.id order.id %}" class="btn btnD1">Deliver Here</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>
            <div class="row">
                <div class="mt-4 ml-3">
                    <button type="button" class="btn btnD2" data-toggle="modal" data-target="#newAddressModal">
                        <i class="fa fa-plus" aria-hidden="true"></i> New Address
                    </button>
                    <a href="{% url 'orders:cancel_pending_order' order.id %}" class="btn btnD1">
                        Cancel the Order
                    </a>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="order-summary">
                <h3 style="font-size: 1.2rem; font-weight: 300;">Summary</h3>
                <h4>
                    <a class="btn w-100 d-flex justify-content-between border-bottom border-top" data-toggle="collapse"
                        href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                        {% with length=order.items.count %}
                        <span>{{ length }} product{{ length|pluralize }} in Order</span>
                        <span><i class="fa fa-angle-down" aria-hidden="true"></i></span>
                        {% endwith %}
                    </a>
                </h4>
                <div class="collapse" id="collapseExample">
                    <table class="table table-mini-cart">
                        <tbody>
                            {% for item in order.items.all %}
                            {% with product=item.product %}
                            <tr>
                                <td class="product-col">
                                    <div class="product-image-container">
                                        <a href="{{ product.get_absolute_url }}">
                                            <img src="{{ product.image.url }}" alt="">
                                        </a>
                                    </div>
                                    <div>
                                        <h4>
                                            <a href="{{ product.get_absolute_url }}">
                                                {{ product.name|truncatewords:"2" }}
                                            </a>
                                        </h4>
                                        <span class="product-qty">Qty: {{ item.quantity }}</span>
                                    </div>
                                </td>
                                <td class="price-col">
                                    ${{ item.get_cost|floatformat:"2" }}
                                </td>
                            </tr>
                            {% endwith %}
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td>Total: </td>
                                <td>${{ order.get_total_cost_after_discount }}</td>
                            </tr>
                            <tr>
                                <td colspan="2" style="padding: 0;">
                                    <a href="{% url 'orders:cancel_pending_order' order.id %}" class="btn btnD1 w-100">
                                        Cancel the Order
                                    </a>
                                </td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal for new address -->
<div class="modal fade bd-example-modal-lg" id="newAddressModal" tabindex="-1" role="dialog"
    aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add New Address</h5>
            </div>
            <div class="modal-body">
                <form method="post" id="addressModalForm">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-12 col-lg-12">
                            {{ address_form.full_name|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-lg-3 mb-0">
                            {{ address_form.country_code|as_crispy_field }}
                        </div>
                        <div class="form-group col-lg-5 mb-0">
                            {{ address_form.phone|as_crispy_field }}
                        </div>
                        <div class="form-group col-lg-4 mb-0">
                            {{ address_form.pin_code|as_crispy_field }}
                        </div>
                    </div>
                    {{ address_form.line_1|as_crispy_field }}
                    {{ address_form.line_2|as_crispy_field }}
                    <div class="form-row">
                        <div class="form-group col-lg-3 mb-0">
                            {{ address_form.landmark|as_crispy_field }}
                        </div>
                        <div class="form-group col-lg-4 mb-0">
                            {{ address_form.city|as_crispy_field }}
                        </div>
                        <div class="form-group col-lg-5 mb-0">
                            {{ address_form.state|as_crispy_field }}
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btnD1" data-dismiss="modal">Close</button>
                <button type="button" class="btn btnD2" id="newAddressBtn">Save</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block extra_scripts %}
<script>
    $(document).ready(function () {

        var showModal = "{{ modal }}";
        if (showModal == "True") {
            $("#newAddressModal").modal('show');
        }

        // $(".address-box").first().addClass('active');
        $(".address-box").on("click", function (e) {
            $(this).parent().siblings().children().removeClass('active');
            $(this).addClass('active');
        });

        $("#newAddressModal input").addClass("form-control-sm");
        $("#newAddressModal select").addClass("form-control-sm");

        $(".remove-btn a").on('click', function (e) {
            e.preventDefault();
            var adr_id = parseInt($(this).data("address-id"));

            $.post({
                url: "{% url 'accounts:address_delete_ajax' %}",
                data: {
                    'adr_id': adr_id,
                },
                dataType: 'json',
                success: function (data) {
                    if (data['status'] == 'ok') {
                        console.log('address deleted');
                        $("#address-box-" + adr_id).parent().remove();
                        alert("Address Deleted successfully!")
                    } else {
                        alert('Sorry, Something went wrong!');
                    }
                }
            })
        });

        $("#newAddressBtn").on('click', function () {
            $("#addressModalForm").submit();
        });

        $("#newAddressModal").on('shown.bs.modal', function () {
            $('.header-nav').css('display', 'none');
        });
        $("#newAddressModal").on('hidden.bs.modal', function () {
            $('.header-nav').css('display', 'block');
        });
    });
        // add onchange validation for fields
        // id_phone 
        // id_pin_code
</script>
{% endblock %}