accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('activate/<uid>/<token>/', views.activate, name='activate'),
    path('myaddress/', views.list_user_address, name='address_list'),
    path('address/create/', views.add_user_address, name='address_create'),
    path('address/edit/<int:adr_id>/', views.edit_user_address, name='address_edit'),
    path('address/delete/<int:adr_id>/', views.delete_user_address, name='address_delete'),
    path('address/delete/ajax/', views.delete_user_address_ajax, name='address_delete_ajax'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('add/ajax/', views.cart_add_ajax, name='cart_add_ajax'),
    path('remove/ajax/',views.cart_remove_ajax, name='cart_remove_ajax'),
    path('clear/', views.cart_clear, name='cart_clear'),
]

maa_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from accounts.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payments/', include('payments.urls', namespace='payments')),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('products.urls', namespace='products')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.conf import settings
from django.db import models
from django.core.mail import send_mail
from django.utils import timezone
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, is_active=True, is_staff=False, is_admin=False):
        if not email:
            raise ValueError(_('Users Must have an Email Address'))
        if not password:
            raise ValueError(_('Users must have a password'))
        
        user_obj = self.model(
            email=self.normalize_email(email)
        )
        user_obj.set_password(password)
        user_obj.active = is_active
        user_obj.staff = is_staff
        user_obj.admin = is_admin
        user_obj.save(using=self._db)
        return user_obj
    
    def create_staffuser(self, email, password=None):
        return self.create_user(email, password, is_staff=True)
    
    def create_superuser(self, email, password=None):
        user = self.create_user(
            email,
            password,
            is_staff=True,
            is_admin=True
        )
        return user


class User(AbstractBaseUser):
    email       = models.EmailField(max_length=255, unique=True)
    first_name  = models.CharField( max_length=255, blank=True, null=True)
    last_name   = models.CharField(max_length=255, blank=True, null=True)
    active      = models.BooleanField( default=True)
    staff       = models.BooleanField( default=False)
    admin       = models.BooleanField( default=False)
    created     = models.DateTimeField(auto_now_add=True)
    #passowrd and last_login are included from AbstractBaseUser class

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    def get_full_name(self):
        return self.first_name + self.last_name
    
    def get_short_name(self):
        return self.first_name or ''
    
    def email_user(self, subject, message, **kwargs):
        send_mail(subject, message, settings.EMAIL_HOST_USER,
                  [self.email], **kwargs)

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_superuser(self):
        return self.admin

    @property
    def is_staff(self):
        return self.admin
    
    @property
    def is_active(self):
        return self.active

class Profile(models.Model):
    GENDER_CHOICES = (
        ('m', 'Male'),
        ('f', 'Female'),
        ('o', 'Other'),
    )
    user            = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic     = models.ImageField(upload_to='user_profile_pic/', blank=True, null=True)
    phone_no        = models.CharField(max_length=17, blank=True, null=True, unique=True)
    gender          = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    confirmed_email = models.BooleanField(default=False)
    confirmed_date  = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.user.email or ''

    def set_confirmed_date(self):
        self.confirmed_date = timezone.now()
        self.save()


class UserAddress(models.Model):
    ADDRESS_TYPE = [
        ("H", "Home"),
        ("O", "Office/Commerial"),
    ]
    user        = models.ForeignKey(User, related_name="addresses", on_delete=models.CASCADE)
    full_name   = models.CharField(max_length=255)
    phone       = models.CharField(max_length=17) # add validation -- through forms
    pin_code    = models.CharField(max_length=6)  # add validation -- through forms
    line_1      = models.CharField(max_length=255)
    line_2      = models.CharField(max_length=255, null=True, blank=True)
    landmark    = models.CharField(max_length=255, null=True, blank=True)
    city        = models.CharField(max_length=255)
    state       = models.CharField(max_length=255)
    address_type= models.CharField(max_length=1, choices=ADDRESS_TYPE, blank=True, null=True)
    created     = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user}'s address '{self.city}, {self.state}' "

accounts/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import UserAddress
import re

User = get_user_model()

class UserAdminCreationForm(forms.ModelForm):
    password1 =  forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)  

    class Meta:
        model =  User
        fields = ('email', )
    
    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError('Email must be Unique!')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Both passwords must be same!")
        return super(UserAdminCreationForm, self).clean(*args, **kwargs)
    
    def save(self, commit=True):
        # user = super(UserAdminCreationForm, self).save(commit=False)
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password2'))
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'active', 'admin')

    def clean_password(self):
        return self.initial["password"] # always return initial value


class UserLoginForm(forms.Form):
    email       = forms.CharField()
    password    = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        email   = self.cleaned_data.get('email').lower()
        pswd    = self.cleaned_data.get('password')
        if email and pswd:
            user_qs = User.objects.filter(email=email)
            if user_qs.exists():
                user = user_qs[0]
                if not user.check_password(pswd):
                    raise forms.ValidationError('Incorrect Password')
                if not user.is_active:
                    raise forms.ValidationError('User NOT active, Contact Us for more Information!')
            user = authenticate(username=email, password=pswd)
            if not user:
                raise forms.ValidationError('Email is not registered Yet!')
            return super(UserLoginForm, self).clean(*args, **kwargs)

class UserRegisterForm(forms.ModelForm):
    email       = forms.EmailField()
    password1   = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2   = forms.CharField(label="Confirm Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2', 'first_name', 'last_name',)

    def clean_email(self):
        email   = self.cleaned_data.get('email')
        qs      = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError('Email already taken, perhaps Logging In!')
        return email.lower()

    def clean_password2(self):
        pwrd1 = self.cleaned_data.get('password1')
        pwrd2 = self.cleaned_data.get('password2')
        if pwrd1 and pwrd2 and pwrd1 != pwrd2:
            raise forms.ValidationError('Password must match!')
        return pwrd2


def phone_number_validator(regex=None, message=None):
    message = "Enter a valid number, select country code from dropdown, 10 digits are allowed"
    if (re.match(r'^\d{3}[-]?\d{3}[-]?\d{4}$', regex)):
        return regex
    else:
        raise forms.ValidationError(message)

class UserAddressForm(forms.ModelForm):
    COUNTRY_CODES = (
        ('+91', '+91'),
        ('+1', '+1'),
    )
    full_name   = forms.CharField(label="Full Name", error_messages={'required': 'Enter your Full Name.'})
    country_code = forms.CharField(max_length=4, widget=forms.Select(
        choices=COUNTRY_CODES), help_text='Choose from dropdown')
    phone       = forms.CharField(max_length=13, help_text='Enter phone number like "123-456-7890" ')
    pin_code    = forms.CharField(label='zip/postal code',max_length=6, help_text='Enter valid pin code')  
    line_1      = forms.CharField(label="Street No.", max_length=255)
    line_2      = forms.CharField(label="Colony, Locality, Village", max_length=255)

    class Meta:
        model = UserAddress
        fields = ('full_name','country_code', 'phone', 'pin_code', 'line_1', 'line_2', 'landmark', 'city', 'state', 'address_type')
    
    def clean_phone(self):
        phone = phone_number_validator(self.cleaned_data.get('phone'))
        cc = self.cleaned_data.get('country_code')
        phone = cc + ' ' + phone
        return phone
    
    def clean_pin_code(self):
        cc = self.cleaned_data.get('country_code')
        value = self.cleaned_data.get('pin_code')
        if len(cc) == 2:
            # US Zip code has 5 didgits only
            print("going in")
            raw_string = r'^[0-9]{5}$'
            message = 'Enter a valid zip code of 5 digits only!'
        else:
            # Indian Pin code has 6 digits only, first number be 0
            raw_string = r'[1-9][0-9]{5}$'
            message = 'Enter a valid, not starting from 0, pin code of 6 digits only!'
        if (re.match(raw_string, value)):
            return value
        else:
            raise forms.ValidationError(message)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.views import login_required
from django.contrib.auth import login, logout, authenticate, get_user_model
from .forms import UserLoginForm, UserRegisterForm, UserAddressForm
from django.contrib import messages
from django.conf import settings
from django.http import JsonResponse
from django.views.decorators.http import require_POST

from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from .tokens import account_activation_token

from .models import UserAddress
from orders.models import Order
# from cart.cart import Cart


User = get_user_model()

# Create your views here.

def login_view(request):
    _next = request.GET.get('next')
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            pswd  = form.cleaned_data.get('password')
            user = authenticate(username=email, password=pswd)
            if user:
                login(request, user)
                # if user has order and not paid
                order_qs = Order.objects.filter(user=user, paid=False)
                if order_qs.exists():
                    order = order_qs[0]

                
                # redirect user to desired path
                if _next:
                    return redirect(_next)
                return redirect('/')
    else:
        form = UserLoginForm()
    return render(request, "accounts/login.html", {'form': form})


@login_required
def logout_view(request):
    logout(request)
    return redirect('accounts:login')

def register_view(request):
    _next = request.GET.get('next')
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data.get('password2')
            user = form.save(commit=False)
            user.set_password(password)
            user.save()
            current_site = get_current_site(request)
            subject = "Activate Your ---- Account"
            message = render_to_string(
                'accounts/account_activation_email.html',{
                    'user': user,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                    'token': account_activation_token.make_token(user),
                }
            )
            user.email_user(subject, message)
            messages.info(request, "An activation link has been sent to your Email!")
            return redirect("accounts:login")
    else:
        form = UserRegisterForm()
    return render(request, "accounts/register.html", {'form': form})


def activate(request, uid, token):
    try:
        u_id = force_text(urlsafe_base64_decode(uid))
        user = User.objects.get(pk=u_id)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    
    if user is not None and account_activation_token.check_token(user, token):
        user.active = True
        user.profile.confirmed_email = True
        user.profile.set_confirmed_date()
        user.save()
        login(request, user)
        messages.success(request, "we have confirmed your email!")
        return redirect("/")
    else:
        messages.error(request, "Account Activation Failed!")
        return render(request, "accounts/activation_invalid.html")

@login_required
def add_user_address(request):
    address_form = UserAddressForm(request.POST or None)
    if address_form.is_valid():
        address = address_form.save(commit=False)
        address.user = request.user
        address.save()
        return redirect('accounts:address_list')
    return render(request, "accounts/address_form.html", {'address_form': address_form})

@login_required
def edit_user_address(request, adr_id):
    address = get_object_or_404(UserAddress, id=adr_id)
    cc, phone = address.phone.split(" ")
    data = {
        'country_code': cc,
        'phone': phone,
    }
    address_form = UserAddressForm(request.POST or None, instance=address, initial=data)
    if address_form.is_valid():
        address_form.save()
        return redirect('accounts:address_list')
    return render(request, "accounts/address_form.html", {'address_form': address_form, 'address': address})

@login_required
def list_user_address(request):
    address_list = UserAddress.objects.filter(user=request.user)
    return render(request, "accounts/address_list.html", {'address_list': address_list})

@login_required
def delete_user_address(request, adr_id):
    address = get_object_or_404(UserAddress, id=adr_id)
    if request.method == 'POST':
        address.delete()
        return redirect('accounts:address_list')
    return render(request, "accounts/address_delete.html", {'address': address})

@require_POST
def delete_user_address_ajax(request):
    data = {
        'status': 'ko',
    }
    adr_id = request.POST.get('adr_id')
    if adr_id:
        try:
            address = UserAddress.objects.get(id=adr_id)
        except UserAddress.DoesNotExist:
            return JsonResponse(data)
        address.delete()
        data['status'] = 'ok'
        return JsonResponse(data)
    return JsonResponse(data)

accounts/templates/accounts/account_activation_email.html
{% autoescape off %}
Hi {{ user.first_name }} {{ user.last_name }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'accounts:activate' uid token %}
{% endautoescape %}

accounts/templates/accounts/activation_invalid.html
{% extends "base.html" %}
{% load static %}
{% block page-title %} Invalid Activation Link {% endblock %}
{% block content %}
    <div class="container">
        <div class="fluid-jumbotron jumbotron">
            <h2 class="display-4">Invalid Activation Link</h2>
            <p class="lead">
                This happens when you have already clicked on activation link.
            </p>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/address_delete.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block extrastyles %}
<link rel="stylesheet" href="#">
{% endblock %}
{% block page_title %}Address - Maa Shop{% endblock %}
{% block content %}
<div class="jumbotron-jumbotron-fluid">
    <div class="container mt-5">
        <div class="address-card m-1 p-1 border">
            <p class="font-weight-bold">{{ address.full_name|title }}</p>
            <p>{{ address.line_2 }}</p>
            <p>{{ address.line_1 }}</p>
            <p>{{ address.city }}, {{ address.state }}</p>
            <p>{{ address.pin_code }}</p>
        </div>
        <form method="post">
            
            {% csrf_token %}
            <p>Are you sure?</p>
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
    </div>

</div>
{% endblock %}

accounts/templates/accounts/address_form.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block extrastyles %}
<link rel="stylesheet" href="#">
{% endblock %}
{% block page_title %}Address - Maa Shop{% endblock %}
{% block content %}
<div class="jumbotron-jumbotron-fluid">
    <div class="container mt-5">
        <form method="post">
            {% csrf_token %}
            {{ address_form|crispy }}
            <button type="submit" class="btn btn-primary">
                {% if address %}
                    Edit & Save
                {% else %}
                    Add Address
                {% endif %}
            </button>
        </form>
    </div>

</div>
{% endblock %}

accounts/templates/accounts/address_list.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block extrastyles %}
<link rel="stylesheet" href="#">
{% endblock %}
{% block page_title %}Address - Maa Shop{% endblock %}
{% block content %}
<div class="jumbotron-jumbotron-fluid">
    <div class="container mt-5">
        <div class="address d-flex">
            {% for adr in address_list %}
                <div class="address-card m-1 p-1 border">
                    <p class="font-weight-bold">{{ adr.full_name|title }}</p>
                    <p>{{ adr.line_2 }}</p>
                    <p>{{ adr.line_1 }}</p>
                    <p>{{ adr.city }}, {{ adr.state }}</p>
                    <p>{{ adr.pin_code }}, {{ adr.phone }}</p>
                    <a href="{% url 'accounts:address_edit' adr.id %}">Edit</a>
                    <a href="{% url 'accounts:address_delete' adr.id %}">delete</a>
                </div>
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block extrastyles %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
{% block page_title %}Login - Maa Shop{% endblock %}
{% block content %}
    <div class="container">
        <div class="grid-wrapper">
            <div class="img-box">
                <img src="{% static 'img/login_cat.jpg' %}" alt="" srcset="">
            </div>
            <div class="content-box">
                <div class="form-wrapper">
                    <h4 class="lead bold ">Login Here.</h4>
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btnD1">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_title %}Sign Up - Maa Shop{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <div class="form-box border p-5 mt-5 rounded">
                <h4 class="display-4">Sign Up Here.</h4>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input type="hidden" name="next">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Sign Up</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}