accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('activate/<uid>/<token>/', views.activate, name='activate'),
    path('myaddress/', views.list_user_address, name='address_list'),
    path('address/create/', views.add_user_address, name='address_create'),
    path('address/edit/<int:adr_id>/', views.edit_user_address, name='address_edit'),
    path('address/delete/<int:adr_id>/', views.delete_user_address, name='address_delete'),
    path('address/delete/ajax/', views.delete_user_address_ajax, name='address_delete_ajax'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('add/ajax/', views.cart_add_ajax, name='cart_add_ajax'),
    path('remove/ajax/',views.cart_remove_ajax, name='cart_remove_ajax'),
    path('clear/', views.cart_clear, name='cart_clear'),
]

maa_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
# from accounts.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payments/', include('payments.urls', namespace='payments')),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('products.urls', namespace='products')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('summary/', views.order_summary, name='order_summary'),
    path('create/<int:adr_id>', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
    path('incomplete/order/<int:order_id>/', views.user_pending_order_action, name='pending_order'),
    path('incomplete/order/update/<int:adr_id>/<int:order_id>/', views.user_pending_order_update, name='pending_order_update'),
    path('cancel/incomplete/<int:order_id>/', views.cancel_pending_order, name='cancel_pending_order'),
    # path('created/', views.order_created, name='order_created'),
]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- fontawesome 4.7 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">

    {% block extrastyles %}
        
    {% endblock %}

    <title>{% block page_title %}{% endblock %}</title>
</head>

<body>
    
    <header>
        {% include "navbar.html" %}
        <div class="container-fluid">
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
            {% endfor %}
        </div>
    </header>
    
    <div class="main-container">
        {% block content %}
    
        {% endblock %}
    </div>

    {% include "footer.html" %}

    {% include 'body_scripts.html' %}
    <script type="text/javascript">
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getCookie('csrftoken');
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
    </script>
    <script type="text/javascript">
        // navbar script
        $(document).ready(function(){
            $('.menu-toggle').click(function(){
                $('div.nav-box').toggleClass('active');
            });
            $('ul li.sub-menu').click(function(){
                $(this).siblings().removeClass('active');
                $(this).parent().parent().siblings().children().children().removeClass('active');
                $(this).toggleClass('active');
            });
            $('ul li.cart-sub-menu').click(function(){
                $(this).siblings().removeClass('active');
                $(this).parent().parent().siblings().children().children().removeClass('active');
                $(this).toggleClass('active');
            });
            $('ul li.sub-menu>a').click(function (event) {
                event.preventDefault();
            });
            $('ul li.cart-sub-menu>a').click(function (event) {
                event.preventDefault();
            });
            // for font-awesome icons, targetting pseudoclass of .fa element
            $('head').append('<style>.fa:before{font-family:fontAwesome;}</style>');
            $('head').append('<style>.fab:before{font-family:fontAwesome;}</style>');

            $("#nav-cart-list").on("click", ".nav-cart-item-remove", function(e){
                e.preventDefault();
                var product_id = parseInt($(this).data("product-id"));
                $.post({
                    url: "{% url 'cart:cart_remove_ajax' %}",
                    data: {
                        'product_id': product_id,
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data.removed == 'ok') {
                            var itemDiv = $("#nav-cart-list").find("#cart-item-" + data.cart_item_product_id);
                            itemDiv.parent().remove();
                            $('#nav-cart-length').text(data.cart_length);
                            $('#nav-cart-total').text('$' + data.cart_total);
                            $("#nav-cart-total-items").text(data.cart_length + " items");



                            if ($("#nav-cart-list").children().length <= 3) {
                                $("#nav-cart-list").children().last().prev().before('<li id="empty-cart"><div>Your cart is Empty</div></li>');
                            } else {
                                $("#nav-cart-list").find('#empty-cart').remove();
                            }

                            alert('Item removed from cart');
                        } else {
                            alert(data.error_message);
                        }
                    }
                });
            });            
        });

        $(window).scroll(function () {
            if ($(window).width() > 991) {
                if($(window).scrollTop() >= 50){
                    $('.header-nav').addClass('scrolled-nav');
                    $('.header-nav .logo').css('font-size', '2.5em');
                } else {
                    $('.header-nav').removeClass('scrolled-nav');
                    $('.header-nav .logo').css('font-size', '3em');
                }
            }else{
                $('.header-nav').css('background-color', '#000');
            }
        });
    </script>
    {% block extra_scripts %}
    {% endblock %}
</body>

</html>

templates/body_scripts.html
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>   

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container">
        <h1>Home.</h1>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block extrastyles %}
	<link rel="stylesheet" href="{% static 'css/index.css' %}">
	<link rel="stylesheet" href="{% static 'css/swiper/swiper.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/smoothproducts/smoothproducts.css' %}">
	<style>
		.sp-wrap{
			max-width: 100%;
			max-height: 70vh;
			overflow-y: hidden;
		}
		.sp-wrap img{
			max-width: inherit;
		}
	</style>
{% endblock %}
{% block content %}

<!-- category slider start -->
<div class="container-fluid">
	<div class="heading-text">
		<h3>Shop by Category</h3>
		<p class="sub-title">Browse in all our categories</p>
	</div>
	<div class="swiper-container">
		<div class="swiper-wrapper">
			{% for cat in con_categories %}
				<div class="swiper-slide">
					<a href="{{ cat.get_absolute_url }}" class="cat-link">
					<div class="category-box">
						<div class="cat-image"><img src="{% if cat.image %}{{ cat.image.url }}{% else %}media/products/2020/03/06/watch1.jpg{% endif %}" alt=""></div>
						<div class="cat-detail">
							<div class="cat-name">{{ cat.name }}</div>
							<div class="cat-products">{{ cat.products.count }} products</div>
						</div>
					</div>
					</a>
				</div>
			{% endfor %}
		</div>
		<div class="swiper-pagination"></div>
	</div>
</div>
<!-- category slider start -->

<!-- sale products start -->
<div class="container-fluid">
	<div class="heading-text">
		<h3>Products on sale</h3>
		<p class="sub-title">Check all our products on sale</p>
	</div>
	<div class="row">
		{% for product in products_on_sale %}
		<div class="col-6 col-md-4 col-lg-3">
			<div class="product-default product">
				<div class="product-image">
					<a href="{{ product.get_absolute_url }}" class="product-image-anchor">
						<img src="{{ product.image.url }}" alt="">
					</a>
					{% if product.discount_percent %}
					<div class="discount-label">{{ product.discount_percent }}% Off</div>
					{% endif %}
					<div class="add-to-cart-btn-icon">
						<a href="add-to-cart/" class="add-to-cart-btn-icon-anchor" data-product-id="{{ product.id }}">
							<i class="fa fa-shopping-bag" aria-hidden="true"></i>
						</a>
					</div>
					<div class="quick-view-btn"><a href="" class="quick-view-btn-anchor" data-product-id="{{ product.id }}">Quick view</a></div>
				</div>
				<div class="product-detail">
					<div class="product-category">
						<a href="{{ product.category.get_absolute_url }}" class="product-category-anchor">{{ product.category }}</a>
					</div>
					<div class="product-title">
						<a href="{{ product.get_absolute_url }}" class="product-title-anchor">{{ product.name|truncatewords:4 }}</a>
					</div>
					<div class="ratings-container">
						<span class="fa fa-star checked"></span>
						<span class="fa fa-star checked"></span>
						<span class="fa fa-star checked"></span>
						<span class="fa fa-star checked"></span>
						<span class="fa fa-star"></span>
					</div>
					<div class="product-price">
						<span class="old-price">${{ product.price }}</span>
						<span class="discount-price">${{ product.get_price }}</span>
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
<!-- sale products end -->

<!-- featured products start -->
<div class="container-fluid bg-light pt-2">
	<div class="heading-text">
		<h3>Featured Products</h3>
		<p class="sub-title">Check all our featured products</p>
	</div>
	<div class="row">
		{% for product in featured_products %}
		<div class="col-6 col-md-4 col-lg-3">
			<div class="product-default product">
				<div class="product-image">
					<a href="{{ product.get_absolute_url }}" class="product-image-anchor">
						<img src="{{ product.image.url }}" alt="">
					</a>
					{% if product.discount_percent %}
					<div class="discount-label">{{ product.discount_percent }}% Off</div>
					{% endif %}
					<div class="add-to-cart-btn-icon">
						<a href="add-to-cart/" class="add-to-cart-btn-icon-anchor" data-product-id="{{ product.id }}">
							<i class="fa fa-shopping-bag" aria-hidden="true"></i>
						</a>
					</div>
					<div class="quick-view-btn"><a href="" class="quick-view-btn-anchor" data-product-id="{{ product.id }}">Quick view</a></div>
				</div>
				<div class="product-detail">
					<div class="product-category">
						<a href="{{ product.category.get_absolute_url }}"
							class="product-category-anchor">{{ product.category }}</a>
					</div>
					<div class="product-title">
						<a href="{{ product.get_absolute_url }}"
							class="product-title-anchor">{{ product.name|truncatewords:4 }}</a>
					</div>
					<div class="ratings-container">
						<span class="fa fa-star checked"></span>
						<span class="fa fa-star checked"></span>
						<span class="fa fa-star checked"></span>
						<span class="fa fa-star checked"></span>
						<span class="fa fa-star"></span>
					</div>
					<div class="product-price">
						<span class="old-price">${{ product.price }}</span>
						<span class="discount-price">${{ product.get_price }}</span>
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
<!-- featured products end -->

<!-- product quick view modal start -->
<!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="product-quick-view" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
	aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">A Quick View</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-lg-6 col-md-6 col-12">
						<div class="modal-product-image">
							<div class="sp-wrap">
								
							</div>
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-12">
						<div class="modal-product-detail">
							<div class="modal-product-name">
								<h4>Short Product Name</h4>
							</div>
							<div class="ratings-container">
								<span class="fa fa-star checked"></span>
								<span class="fa fa-star checked"></span>
								<span class="fa fa-star checked"></span>
								<span class="fa fa-star checked"></span>
								<span class="fa fa-star"></span>
							</div>
							<div class="product-price mt-2">
								<span class="old-price">$59.99</span>
								<span class="discount-price">$49.99</span>
							</div>
							<div class="modal-product-desc mt-3">
								<p></p>
							</div>
							<div class="modal-product-actions mt-2">
								<button type="submit" class="btn btnD1" id="quick-modal-cart" data-product-id="" data-quick-modal="true">
									<i class="fa fa-shopping-bag" aria-hidden="true"></i> Add to cart
								</button>
								<a href="#" class="btn btnD1 px-3" id="quick-modal-wishlist"><i class="fa fa-heart"></i></a>
							</div>
							<div class="modal-product-share mt-2">
								<ul class="share-actions">
									<li>Share: </li>
									<li><a href=""><i class="fa fa-facebook"></i></a></li>
									<li><a href=""><i class="fa fa-twitter"></i></a></li>
									<li><a href=""><i class="fa fa-pinterest"></i></a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- product quick view modal end -->



{% endblock %}
{% block extra_scripts %}
	<script src="{% static 'js/swiper/swiper.min.js' %}"></script>
	<script src="{% static 'js/smoothproducts/smoothproducts.js' %}"></script>
	<script>
		var swiper = new Swiper('.swiper-container', {
			slidesPerView: 'auto',
			spaceBetween: 15,
			pagination: {
				el: '.swiper-pagination',
				clickable: true,
			},
			autoplay: {
				delay: 2500,
				disableOnInteraction: false,
			},
		});
	</script>
	<script>
		$(document).ready(function(){
			// product list catalog script
			$('.add-to-cart-btn-icon-anchor , #quick-modal-cart').on("click", function(e){
				e.preventDefault();
				var product_id = parseInt($(this).data("product-id"));
				var is_modal = $(this).data("quick-modal");
				var btn = $(this);
				if(is_modal){
					console.log("before", $(this).text());
				}

				$.post({
					url: "{% url 'cart:cart_add_ajax' %}",
					data: {
						product_id: product_id,
					},
					dataType: 'json',
					success: function (data) {
						if (data.added == 'ok') {
							$('#nav-cart-length').text(data.cart_length);
							$('#nav-cart-total').text('$' + data.cart_total);
							$("#nav-cart-total-items").text(data.cart_length + " items");

							added_item = data.added_item;
							var itemDiv = $("#nav-cart-list").find("#cart-item-" + data.added_item.cart_item_product_id);
							if (itemDiv.length) {
								var detailDiv = itemDiv.children().first()
								detailDiv.find('span').text(data.added_item.quantity + ' x $' + data.added_item.price);
							} else {
								// adding new list divElement
								itemDiv = $('#new-nav-cart-item').html();
								$("#nav-cart-list").children().last().prev().before(itemDiv);

								var addedElementDiv = $("#nav-cart-list").children().eq(-3).children();

								addedElementDiv.css('display', 'flex');
								addedElementDiv.attr("id", "cart-item-" + added_item.cart_item_product_id);

								var detailDiv = addedElementDiv.children().first();
								detailDiv.find('.product-name').attr("href", added_item.product_url);
								detailDiv.find('.product-name').text(added_item.product_name); // added truncated string
								detailDiv.find('span').text(added_item.quantity + ' x $' + added_item.price);

								var imageDiv = addedElementDiv.children().last();
								imageDiv.find('img').attr("src", added_item.product_image_url);
								imageDiv.find(".nav-cart-item-remove").data("product-id", added_item.cart_item_product_id);

								// if from quick view modal
							}

							if($("#empty-cart").length){
								$("#empty-cart").remove();
							}


							if(is_modal){
								btn.html('<i class="fa fa-shopping-bag" aria-hidden="true"></i> Go to cart');
							}
							alert('Item Added to cart!!');
						} else {
							alert(data.error_message);
						}

					}
				});
			});

			$('.quick-view-btn-anchor').on("click", function(e){
				e.preventDefault();
				var product_id = parseInt($(this).data("product-id"));

				$.ajax({
					url: '/product-detail/ajax/'+product_id+'/',
					data:{},
					dataType: 'json',
					success: function(data){
						if(data.status == 'ok'){
							var item = data.item;
							var image_list = JSON.parse(data.product_image_list);

							// add item data to modal html
							var modalProductImage = $('.modal-body').children().first().children().first();
							// add product image
							modalProductImage.find('.sp-wrap').append($('<a/>', {
								'href': item.product_image_url
							}).append($('<img/>', {
								'src': item.product_image_url
							})));

							// add product other images
							for (const img_url of image_list) {
								modalProductImage.find('.sp-wrap').append($('<a/>', {
									'href': img_url
								}).append($('<img/>', {
									'src': img_url
								})));
							}
							// add detail info
							var modalProductDetail = $('.modal-body').children().last().children().last();
							modalProductDetail.find(".modal-product-name h4").text(item.product_name);
							modalProductDetail.find(".old-price").text('$'+ item.product_original_price);
							modalProductDetail.find(".discount-price").text('$'+ item.product_current_price);
							modalProductDetail.find(".modal-product-desc p").text(item.product_short_desc);
							
							modalProductDetail.find("#quick-modal-cart").data("product-id", item.product_id);
							modalProductDetail.find("#quick-modal-wishlist").data("product-id", item.product_id);

							$('.sp-wrap').smoothproducts();
							$('#product-quick-view').modal('show');
						}else{
							alert(data.error_message);
						}
					}
				})
			});

			$("#product-quick-view").on("click", "#quick-modal-cart", function(e){
				e.preventDefault();
			});

			$('#product-quick-view').on('hidden.bs.modal',function(){
				$('#quick-modal-cart').html('<i class="fa fa-shopping-bag" aria-hidden="true"></i> Add to cart')
				$('.sp-wrap').html('')
				$(".header-nav").css('display', 'block');
			});
			$('#product-quick-view').on('shown.bs.modal',function(){
				$(".header-nav").css('display', 'none');
			})

			
		});
	</script>
{% endblock %}

templates/navbar.html
<div class="header-nav">
    <div class="logo">LOGO</div>
    <div class="nav-box">
        <nav class="nav-left">
            <ul>
                <li><a href="/">home</a></li>
                <li><a href="">about</a></li>
                <li class="sub-menu">
                    <a href="">catgories</a>
                    <ul>
                        {% for cat in con_categories %}
                            <li><a href="{{ cat.get_absolute_url }}">{{ cat.name|title }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                {% if user.is_authenticated %}
                    <li><a href="">Orders</a></li>
                {% endif %}
                <li><a href="">contact</a></li>
            </ul>
        </nav>
        <nav class="nav-right">
            <ul>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i></a></li>
                    <li><a href=""><i class="fa fa-heart-o" aria-hidden="true"></i></a></li>
                {% else %}
                    <li><a href=""><i class="fa fa-user" aria-hidden="true"></i></a></li>
                {% endif %}
                <li><a href=""><i class="fa fa-search" aria-hidden="true"></i></a></li>
                <li class="cart-sub-menu">
                    <a href="">
                        <i class="fa fa-shopping-bag" aria-hidden="true"></i>
                        <span id="nav-cart-length">{{ cart|length }}</span>
                    </a>
                    <ul id="nav-cart-list">
                        <li>
                            <div>
                                <span id="nav-cart-total-items">{{ cart|length }} items</span>
                                <span><a href="{% url 'cart:cart_detail'%}">View Cart</a></span>
                            </div>
                        </li>
                        {% if cart|length > 0 %}
                            {% for item in cart %}
                                {% with product=item.product %}
                                <li>
                                    <div class="cart-item" id="cart-item-{{ product.id }}">
                                        <div class="item-detail">
                                            <a href="{{ product.get_absolute_url }}" class="product-name">
                                                {{ product.name|truncatewords:2 }}
                                            </a><br>
                                            <span>{{ item.quantity }} x ${{ product.get_price }}</span>
                                        </div>
                                        <div class="item-image">
                                            <a href="remove-from-cart/" class="nav-cart-item-remove" data-product-id="{{ product.id }}"><i class="fa fa-times"></i></a>
                                            <img src="{{ product.image.url }}" alt="">
                                        </div>
                                    </div>
                                </li>
                                {% endwith %}
                                {% endfor %}
                        {% else %}
                            <li id="empty-cart"><div>Your cart is Empty</div></li>
                        {% endif %}
                        <li>
                            <div class="cart-total">
                            <span>Total:</span>
                            <span id="nav-cart-total">${{ cart.get_total_price }}</span>
                            </div>
                        </li>
                        <li><a href="{% url 'orders:order_summary' %}" class="checkout">checkout</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
    <div class="menu-toggle">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
</div>
<div id="new-nav-cart-item" style="display: none;">
    <li>
        <div class="cart-item" id="cart-item-{{ product.id }}">
            <div class="item-detail">
                <a href="{{ product.get_absolute_url }}" class="product-name">
                    {{ product.name|truncatewords:2 }}
                </a><br>
                <span>{{ item.quantity }} x ${{ product.get_price }}</span>
            </div>
            <div class="item-image">
                <a href="" class="nav-cart-item-remove"><i class="fa fa-times"></i></a>
                <img src="{{ product.image.url }}" alt="">
            </div>
        </div>
    </li>
</div>

templates/paginator.html
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if products.has_previous %}
        <li class="page-item">
            <a class="page-link"
                href="?page={{ products.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"
                tabindex="-1"><i class="fa fa-angle-double-left" aria-hidden="true"></i> </a></a>
        </li>
        {% endif %}

        {% for num in products.paginator.page_range %}
            {% if num == products.number %}
                <li class="page-item">
                    <a class="page-link font-weight-bold text-dark" href="?page={{ num }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ num }}</a>
                </li>
            {% elif num > products.number|add:'-2' and num < products.number|add:'2' %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if products.has_next %}
        <li class="page-item">
            <a class="page-link"
                href="?page={{ products.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i class="fa fa-angle-double-right" aria-hidden="true"></i> </a></a>
        </li>
        {% endif %}
    </ul>
</nav>